import "@/app/(main)/globals.css";
import { AppProvider } from "@/components/providers";
import { AppOptions } from "@/components/providers/app-provider";
import { getSession } from "@/features/auth";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Endatix Form",
  description: "Generated by Endatix",
};

export default async function ShareLayout({ 
  children 
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background font-sans antialiased">
        <AppProvider options={AppOptions.NoTheme} session={session}>
          <div className="flex min-h-screen flex-col">
            <main className="flex-1">{children}</main>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
