import { auth } from "@/auth";
import { AppProvider } from "@/components/providers";
import { AppOptions } from "@/components/providers/app-provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Endatix Form",
  description: "Generated by Endatix",
  generator: "Endatix",
  keywords: ["share", "form", "survey"],
  applicationName: "Endatix Hub",
  publisher: "Endatix Ltd.",
  robots: {
    index: false,
    follow: false,
  },
};

export default async function ShareLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://www.google.com" />
        <link rel="preconnect" href="https://www.gstatic.com" crossOrigin="" />
        <link rel="icon" href="/assets/icons/icon.svg" type="image/svg+xml" />
      </head>
      <body>
        <AppProvider options={AppOptions.PublicPages} session={session}>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
