import { ApiResult } from "../shared/api-result";
import { appendDateRangeFilters, appendSortParams } from "../shared/list-query";
import {
  normalizePagedResponse,
  type NormalizedPagedResponse,
} from "../shared/paged-response";
import {
  appendPagingQueryParams,
  appendQueryParam,
  buildEndpointWithQuery,
} from "../shared/query-params";
import type { PagedResponse } from "../shared/types";
import type { EndatixApi } from "../endatix-api";
import { Result } from "@/lib/result";
import { validateEndatixId } from "@/lib/utils/type-validators";
import type {
  CreatePlatformTenantRequest,
  ListPlatformTenantsRequest,
  PlatformTenant,
  PlatformTenantListItem,
  UpdatePlatformTenantRequest,
} from "./types";

const TENANTS_BASE = "/admin/tenants";
const DEFAULT_PAGE = 1;
const DEFAULT_PAGE_SIZE = 10;

export type PlatformTenantsPage =
  NormalizedPagedResponse<PlatformTenantListItem>;

export function buildListPlatformTenantsEndpoint(
  request: ListPlatformTenantsRequest = {},
): string {
  const searchParams = new URLSearchParams();
  appendPagingQueryParams(searchParams, request, {
    page: DEFAULT_PAGE,
    pageSize: DEFAULT_PAGE_SIZE,
  });
  appendSortParams(searchParams, request);
  appendDateRangeFilters(searchParams, request, ["created", "modified"]);
  appendQueryParam(searchParams, "search", request.search);
  return buildEndpointWithQuery(TENANTS_BASE, searchParams);
}

export default class PlatformTenants {
  constructor(private readonly endatix: EndatixApi) {}

  async list(
    request: ListPlatformTenantsRequest = {},
  ): Promise<ApiResult<PlatformTenantsPage>> {
    const response = await this.endatix.get<
      PagedResponse<PlatformTenantListItem>
    >(buildListPlatformTenantsEndpoint(request));
    if (!response.success) {
      return response;
    }

    return ApiResult.success(normalizePagedResponse(response.data));
  }

  async getById(tenantId: string): Promise<ApiResult<PlatformTenant>> {
    const idResult = validateEndatixId(tenantId, "tenantId");
    if (Result.isError(idResult)) {
      return ApiResult.validationError(idResult.message);
    }

    return this.endatix.get<PlatformTenant>(
      `${TENANTS_BASE}/${idResult.value}`,
    );
  }

  /** The short URL is generated by the API; never send a slug. */
  async create(
    request: CreatePlatformTenantRequest,
  ): Promise<ApiResult<PlatformTenant>> {
    return this.endatix.post<PlatformTenant>(TENANTS_BASE, request);
  }

  async update(
    tenantId: string,
    request: UpdatePlatformTenantRequest,
  ): Promise<ApiResult<PlatformTenant>> {
    const idResult = validateEndatixId(tenantId, "tenantId");
    if (Result.isError(idResult)) {
      return ApiResult.validationError(idResult.message);
    }

    return this.endatix.patch<PlatformTenant>(
      `${TENANTS_BASE}/${idResult.value}`,
      request,
    );
  }
}
