import type { PdfTheme } from "@/features/pdf-export/pdf-theme";

export type PdfThemeStyles = ReturnType<typeof createPdfThemeStyles>;

export function createPdfThemeStyles(theme: PdfTheme) {
  const body = theme.fontSize;
  const small = Math.max(8, body - 2);
  const title = body + 2;

  return {
    page: {
      padding: 20,
      fontSize: body,
      fontFamily: "Roboto",
      backgroundColor: theme.pageBackground,
      color: theme.text,
    },
    sectionTitle: {
      fontSize: title,
      marginBottom: 8,
      fontFamily: "Roboto-Bold",
      color: theme.text,
    },
    questionTitle: {
      fontSize: body,
      fontFamily: "Roboto-Bold",
      marginBottom: 2,
      color: theme.text,
    },
    questionSubTitle: {
      fontFamily: "Roboto",
      fontSize: small,
      width: "100%",
      color: theme.mutedText,
    },
    propertiesSection: {
      fontSize: small,
      backgroundColor: theme.surface,
      borderRadius: theme.radius,
      gap: 4,
      borderWidth: 1,
      borderColor: theme.border,
    },
    propertyLabel: {
      flex: 2,
      textAlign: "right" as const,
      fontFamily: "Roboto-Bold",
      color: theme.mutedText,
      fontSize: small,
      paddingRight: 16,
    },
    propertyValue: {
      flex: 3,
      textAlign: "left" as const,
      fontFamily: "Roboto",
      color: theme.text,
      fontSize: small,
    },
    accentBar: {
      height: 6,
      backgroundColor: theme.primary,
      marginBottom: 12,
    },
    answerRow: {
      borderBottomColor: theme.border,
    },
    groupHeaderText: {
      fontSize: body + 1,
      fontFamily: "Roboto-Bold",
      color: theme.text,
      paddingVertical: 2,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      width: "100%",
    },
    invisibleText: {
      fontSize: small,
      color: theme.mutedText,
      marginLeft: 4,
    },
    answerField: {
      backgroundColor: theme.inputBackground,
      borderRadius: theme.radius,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 6,
    },
    answerText: {
      fontFamily: "Roboto",
      fontSize: small,
      color: theme.text,
    },
    questionLabel: {
      fontFamily: "Roboto-Bold",
      fontSize: body,
      marginBottom: 4,
      flexGrow: 1,
      color: theme.text,
    },
    mutedText: {
      color: theme.mutedText,
      fontSize: small,
    },
    chip: {
      backgroundColor: theme.inputBackground,
      color: theme.text,
      paddingTop: 2,
      paddingBottom: 2,
      paddingLeft: 4,
      paddingRight: 4,
      borderRadius: Math.min(theme.radius, 6),
      fontSize: small,
      fontFamily: "Roboto",
      borderWidth: 1,
      borderColor: theme.border,
    },
    table: {
      width: "auto" as const,
      borderStyle: "solid" as const,
      borderWidth: 1,
      borderColor: theme.border,
      borderRightWidth: 0,
      borderBottomWidth: 0,
      marginTop: 8,
    },
    tableRow: {
      flexDirection: "row" as const,
      alignItems: "stretch" as const,
      minHeight: 20,
    },
    tableHeader: {
      backgroundColor: theme.inputBackground,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    tableCell: {
      fontSize: small,
      fontFamily: "Roboto",
      color: theme.text,
      padding: 4,
      borderStyle: "solid" as const,
      borderWidth: 1,
      borderColor: theme.border,
      borderLeftWidth: 0,
      borderTopWidth: 0,
      flexShrink: 1,
      flexGrow: 1,
      wordBreak: "break-word" as const,
      minWidth: 50,
      flex: 1,
    },
    tableCellHeader: {
      fontSize: small,
      fontFamily: "Roboto-Bold",
      color: theme.text,
      textAlign: "center" as const,
      padding: 4,
      borderStyle: "solid" as const,
      borderWidth: 1,
      borderColor: theme.border,
      borderLeftWidth: 0,
      borderTopWidth: 0,
      flexShrink: 1,
      flexGrow: 1,
      wordBreak: "break-word" as const,
      minWidth: 50,
      flex: 1,
    },
    tableCaption: {
      fontSize: small + 1,
      fontFamily: "Roboto-Bold",
      color: theme.text,
      marginBottom: 6,
    },
    noAnswer: {
      fontSize: small,
      color: theme.mutedText,
      marginTop: 4,
    },
    stackedContainer: {
      marginTop: 8,
      borderStyle: "solid" as const,
      borderWidth: 1,
      borderColor: theme.border,
      borderRightWidth: 0,
      borderBottomWidth: 0,
    },
    stackedRow: {
      padding: 6,
      borderStyle: "solid" as const,
      borderWidth: 1,
      borderColor: theme.border,
      borderLeftWidth: 0,
      borderTopWidth: 0,
      backgroundColor: theme.surface,
    },
    stackedRowLabel: {
      fontSize: small,
      fontFamily: "Roboto-Bold",
      color: theme.text,
      marginBottom: 2,
    },
    stackedRowCell: {
      fontSize: small,
      fontFamily: "Roboto",
      color: theme.text,
      marginBottom: 1,
    },
    panelDivider: {
      marginBottom: 12,
      borderTopWidth: 1,
      borderTopColor: theme.border,
      paddingTop: 8,
    },
    positive: {
      color: theme.positive,
    },
    negative: {
      color: theme.negative,
    },
    checkboxBox: {
      width: 12,
      height: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
    },
    formInput: {
      height: 18,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.inputBackground,
      color: theme.text,
      fontSize: small,
      fontFamily: "Roboto",
      paddingHorizontal: 4,
    },
    formList: {
      height: 54,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.inputBackground,
      color: theme.text,
      fontSize: small,
      fontFamily: "Roboto",
    },
    stack: {
      flexDirection: "column" as const,
      gap: 4,
    },
    row: {
      flexDirection: "row" as const,
      alignItems: "center" as const,
      gap: 4,
    },
  };
}
