import { AppProvider } from "@/components/providers";
import { getSession } from "@/features/auth";
import "@/app/globals.css";
import { AppOptions } from "@/components/providers/app-provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface SlackLayoutProps {
  children: React.ReactNode;
}

export default async function SlackLayout({ children }: SlackLayoutProps) {
  const session = await getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background font-sans antialiased">
        <AppProvider options={AppOptions.NoTheme} session={session}>
          <div className="flex min-h-screen flex-col">{children}</div>
        </AppProvider>
      </body>
    </html>
  );
}
