export enum QuestionType {
  Text = "text",
  Boolean = "boolean",
  Rating = "rating",
  Radiogroup = "radiogroup",
  Checkbox = "checkbox",
  Dropdown = "dropdown",
  Ranking = "ranking",
  Comment = "comment",
  File = "file",
  PanelDynamic = "paneldynamic",
  SignaturePad = "signaturepad",
  Matrix = "matrix",
  MatrixDropdown = "matrixdropdown",
  MatrixDynamic = "matrixdynamic",
  MultipleText = "multipletext",
  TagBox = "tagbox",
  Custom = "custom",
  AudioRecorder = "audiorecorder",
  Unsupported = "unsupported",
}
