export enum QuestionType {
  Text = "text",
  Boolean = "boolean",
  Checkbox = "checkbox",
  Rating = "rating",
  Radiogroup = "radiogroup",
  Dropdown = "dropdown",
  Ranking = "ranking",
  Matrix = "matrix",
  Comment = "comment",
  File = "file",
  SignaturePad = "signaturepad",
  Video = "video",
  MultipleText = "multipletext",
  Unsupported = "unsupported",
}
